#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Ripcord.Engine.Shred;
using Ripcord.Receipts.Model;
using Ripcord.Receipts.Export;

namespace Ripcord.App.Services
{
    /// <summary>
    /// Listens to a Shred run and captures enough data to emit a Receipt + Attestation (unsigned by default).
    /// </summary>
    public sealed class ReceiptEmitter
    {
        private readonly ILogger<ReceiptEmitter> _log;
        private readonly ReceiptJsonExporter _json;

        public string ReceiptRoot { get; } =
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), "Ripcord", "Receipts");

        public ReceiptEmitter(ILogger<ReceiptEmitter> log, ReceiptJsonExporter json)
        {
            _log = log;
            _json = json;
        }

        public async Task EmitAsync(Guid jobId,
                                    ShredJobRequest request,
                                    ShredJobResult result,
                                    IReadOnlyList<(string path, long size, bool deleted)> observedItems,
                                    DateTimeOffset startedUtc,
                                    DateTimeOffset completedUtc)
        {
            Directory.CreateDirectory(ReceiptRoot);

            var items = observedItems.Select(o => new Receipt.ReceiptItem(
                Path: o.path,
                SizeBytes: Math.Max(0, o.size),
                Deleted: o.deleted,
                Passes: request.Profile.Passes.Count,
                AdsBefore: -1,
                AdsAfter: -1,
                VerificationOk: null,
                VerificationSampleFraction: null,
                Ranges: null,
                Shadow: null,
                Notes: null)).ToList();

            var receipt = Receipt.Create(
                jobId: jobId,
                startedUtc: startedUtc,
                completedUtc: completedUtc,
                machine: Environment.MachineName,
                user: Environment.UserName,
                profileId: request.Profile.Id,
                profileName: request.Profile.DisplayName,
                dryRun: request.DryRun,
                items: items,
                stats: new Receipt.ReceiptStats(result.FilesProcessed, result.FilesFailed, (int)result.FilesDeleted, result.BytesOverwritten),
                journalFiles: null,
                freeSpace: null,
                notes: new[] { "Generated by Ripcord.App" });

            var att = Attestation.FromReceipt(receipt); // unsigned (you can sign later with a cert)

            var paths = await _json.ExportAsync(receipt, att, ReceiptRoot, baseFileName: $"job_{jobId:N}");
            _log.LogInformation("Receipt saved at {ReceiptPath}", paths.ReceiptPath);
        }
    }
}
